name: drosophila_trader
description: DROSOPHILA TRADER v2.0 - 1-minute scalp signal client for BTC and PAXG.
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  web_socket_channel: ^3.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
