"""Reading guides for the sub-categories whose module left ``interpretation``
empty.  ``all_variants()`` fills them in, so every one of the 2,100 formulas
tells the dashboard how to read its number (the Round E rule: logics too)."""

INTERPRETATIONS = {
    (3, "KL divergence"): "KL grows when the recent window has drifted from the long one; the sign of the mean shift is the direction to follow while KL is rising, fade when it collapses",
    (3, "Jeffreys divergence"): "symmetric gap between recent and long Gaussians; large J in the recent mean's direction = genuine drift, tiny J = nothing has changed",
    (3, "exponential family projection"): "m-projection of the recent window onto the long family; the residual natural parameter points where the distribution is moving",
    (3, "geodesic flow"): "velocity along the Fisher-Rao geodesic from the old (μ,σ) to the new; positive = the mean is being carried up along the shortest statistical path",
    (3, "mixture family"): "weight of the 'up' component in a two-Gaussian mixture of recent returns; > ½ the up-mode dominates",
    (4, "Sinkhorn"): "entropic optimal-transport cost from the ask side to the bid side; mass moving toward bids (cheaper to transport down) is bearish, toward asks bullish",
    (4, "barycenter"): "Wasserstein barycenter of recent book snapshots versus the current mid; mid above the barycenter = the book is being lifted",
    (4, "transport plan (centroid)"): "centroid of the optimal plan between buy- and sell-trade price distributions; a centroid above mid says buyers paid up",
    (4, "multi-marginal transport"): "joint transport across price, volume and imbalance marginals; the signed cost difference says which side is dislocated",
    (5, "fractional Itô (Grünwald-Letnikov)"): "fractional derivative of order α of the window-relative log price; positive D^α = momentum with memory, negative = decaying",
    (5, "fractional Ornstein-Uhlenbeck"): "deviation from the long-memory mean scaled by the fractional reversion speed; the sign is the pull back toward the mean",
    (5, "volatility of volatility"): "ratio of recent to long vol-of-vol; a vol-of-vol spike with a signed move continues, a quiet one mean-reverts",
    (6, "tropical root"): "distance of the current log price from the nearest tropical root (kink) of the max-plus polynomial; crossing a root flips the dominant monomial",
    (6, "Newton polygon"): "convexity of the Newton polygon of recent moves; a convex lower hull says higher-order terms (acceleration) dominate the drift's sign",
    (6, "tropical curve"): "which side of the tropical curve (max-plus zero set) the (price, volume) point lies on",
    (6, "min-plus algebra"): "min-plus shortest path through the drawdown lattice; a shortening path = the floor is near, lengthening = still falling",
    (6, "tropical determinant"): "tropical determinant (assignment optimum) of the OHLC matrix; its sign-weighted change tracks where extremes cluster",
    (6, "tropical linear space"): "projection of the current bar onto the tropical linear space spanned by recent bars; a residual above the space = breakout",
    (6, "tropical intersection"): "stable intersection count of price and volume tropical curves; more intersections = regime boundary, follow the fresh drift",
    (6, "tropical eigenvector"): "max-plus eigenvector of the up/flat/down transition matrix; weight on the 'up' coordinate minus 'down'",
    (7, "entanglement entropy"): "mutual information between price and volume indicator states; high entanglement with a signed price state is a trend, low is noise",
    (7, "decoherence rate"): "how fast off-diagonal coherence of the density matrix decays; fast decoherence = the pure trend state is collapsing",
    (7, "quantum walk"): "drift of a discrete quantum walk driven by the sign sequence; ballistic spreading in one direction = persistent sign",
    (7, "POVM measurement"): "probability of the 'up' outcome under a positive operator-valued measurement of the indicator bank",
    (7, "quantum channel"): "trace distance between the state before and after the latest candle's channel; a large signed change = information arrived",
    (7, "quantum Bayes"): "posterior of the up-state after Lüders update with the latest observation; above ½ = lean up",
    (7, "Wigner function (Bloch)"): "position on the Bloch sphere of the 2-state projection; z > 0 is the up pole, |xy| is coherence",
    (8, "p-adic wavelet"): "p-adic Haar coefficient of tick moves at scale p^j; a positive coefficient is a coarse-scale up imbalance",
    (8, "p-adic integration"): "Volkenborn integral of the tick-move sequence; the signed mean over p-adic balls",
    (8, "Hensel lifting"): "residue of the next move predicted by lifting the recent residues mod p^k; the lifted sign is the direction",
    (8, "p-adic L-function"): "Legendre-symbol weighted momentum over the last n ticks; positive when quadratic-residue moves have been upward",
    (8, "Iwasawa theory"): "slope of the tower of p-adic valuations across scales; rising tower = larger and larger moves, in the recent sign",
    (8, "p-adic Hodge"): "drift between valuation classes (small-tick vs big-tick regimes); a shift toward large valuations in one direction is conviction",
    (8, "p-adic modular form"): "Hecke-operator average of the valuation sequence; its sign is the resonant direction",
    (8, "p-adic interpolation"): "p-adic interpolation of the move sequence to the next index; interpolated sign = predicted direction",
    (9, "limit"): "the limit (agreement) of the timeframe diagram: only fires when every timeframe functor agrees on a side",
    (9, "colimit"): "the colimit (union) of timeframe readings: the dominant side across timeframes, weighted by how many agree",
    (9, "adjunction"): "unit of the coarse⊣fine adjunction: the residual between the coarse view lifted to fine and the fine view itself",
    (9, "monad"): "the EMA monad's multiplication term μ: the correction between smoothing once and smoothing twice",
    (9, "Kan extension"): "left Kan extension of the short timeframe along the long one; the extended value minus the actual = latent drift",
    (9, "Yoneda"): "Yoneda-style nearest neighbours: the asset is what it does to every probe window; the neighbours' next move is the forecast",
    (9, "topos"): "truth value of 'the trend is up' in the subobject classifier built from timeframe agreements (0 … 1, centred)",
    (9, "enriched / derived (cross-asset functor)"): "the functor from the other asset: lead-lag enriched by correlation; the other asset's recent move mapped onto this one",
    (10, "conditional complexity"): "K(price | volume) approximated by compressed sizes; low conditional complexity = volume explains price, follow the volume sign",
    (10, "Kolmogorov complexity"): "zlib size of the symbolised tape; a compressible tape is predictable, the recent sign continues",
    (10, "effective dimension"): "effective dimension of the delay embedding; low dimension with signed drift = structured move",
    (10, "block entropy"): "block-entropy Markov predictor: P(up | last k symbols) − P(down | last k symbols)",
    (10, "Chaitin Ω"): "halting-probability-style weight of the rule library: the share of rules that fire 'up' minus 'down'",
    (10, "logical depth"): "steps the Markov predictor needs to converge; shallow depth = the pattern is already decided, go with it",
    (10, "sophistication"): "MDL sophistication: model bits versus noise bits; a sophisticated (structured) tape continues its sign, a noisy one does not",
}
